spring:
  profiles:
    active: default

server:
  port: 9090
  tomcat:
    threads:
      max: 512
  servlet:
    context-path: /v1/kms
    encoding:
      charset: UTF-8
      enabled: true
      force: true

aws:
  kms:
    keyId: 키 아이디
    encryptionAlgorithm: "RSAES_OAEP_SHA_256"
